version: "3"
services:
  puppeteer-emulator:
    build:
      context: ./services/puppeteer_emulator
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: /bin/sh
    volumes:
      - ./services/puppeteer_emulator/src:/usr/src/app/src
      - ./services/puppeteer_emulator/main.js:/usr/src/app/main.js
      - ./services/puppeteer_emulator/package.json:/usr/src/app/package.json
      - ./services/puppeteer_emulator/yarn.lock:/usr/src/app/yarn.lock
      - ./CODE:/usr/src/app/CODE
    env_file:
      - ./.env
